### ISSUE TITLE
Do the README/Vignette  trick for tidybulk

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidybulk#105]
Hello @mblue9 , can you confirm that we cannot do the same trick we did for tidyseurat, here for tidybulk?

**Comment by mblue9** [comment]
I can doublecheck with the new changes but when I last tried it didn't work with BiocCheck. If I confirm it doesn't work I could submit an issue to BiocCheck repo to ask if there's a way to make it work. What do you think?

**Comment by mblue9** [comment]
xref https://github.com/stemangiola/tidybulk/pull/111
Confirmed it doesn't work. It's due to a known issue with BiocCheck.

**Comment by stemangiola** [comment]
Noooo. Are they going to fix it? Because they should.

**Comment by mblue9** [comment]
Fingers crossed they will. But I saw that BiocCheck issue has the comment 

>Although usually not a lot of packages use this functionality...

I added my 👍 vote to that issue maybe you could too? So they know some of us would REALLY like it to be fixed 😄

**Comment by mblue9** [comment]
If this PR passes https://github.com/stemangiola/tidybulk/pull/169 this is done.
