### ISSUE TITLE
double check DESeq2

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidybulk#113]
Hello @mblue9 , I ave some strange results from DESeq2 and I double checked, I was wondering if you could have a quick eye.

![image](https://user-images.githubusercontent.com/7232890/94261695-a30cc100-ff75-11ea-8815-788292c612b2.png)

**Comment by mblue9** [comment]
Ok can you point me to the code you’re using & I’ll have a look?

**Comment by stemangiola** [comment]
Even better, would you mind doing an independent edgeR and deseq2 analysis (better if not with tidybulk) of Pasilla with this formula ~ condition + type

(FYI the function for deseq2 is called get_differential_transcript_abundance_deseq2 in functions.R)

I verified if the conversion to SE was causing mess, but the SE object that goes into deseq2 seems ok, and yet the fold changes are totally unrelated.

**Comment by stemangiola** [comment]
Maybe the error is in the contrast for deseq2 maybe I am getting the statistics for the confounder and not the factor of interest

**Comment by mblue9** [comment]
Sorry only got to reply now yep it needs to be e.g. `~type + condition` for deseq2 as shown in the [vignette](https://www.bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#differential-expression-analysis), glad you figured it out 👍

**Comment by mblue9** [comment]
Heya just had a thought here,  you have now flipped the deseq2 order of contrasts in tidybulk to match edgeR/limma is that right? i.e like in the workshop we use `~condition + type` instead of `~type + condition` for deseq2, same as the others. But is that documented anywhere in tidybulk so deseq2 users will know?

**Comment by stemangiola** [comment]
> But is that documented anywhere in tidybulk so deseq2 users will know?

no :)

**Comment by mblue9** [comment]
Ok :) So would something like this make sense?
"@param .formula A formula representing the desired linear model. If there is more than one factor, they should be in the order `primary factor + additional factors`"

Also if deseq2 input formula is being altered by tidybulk to be similar to edgeR/limma-voom then would it make sense to have the contrasts input in a similar format e.g. also use dextrt-dexuntrt instead of dex,trt,untrt for deseq2 or would that be too tricky to implement?

**Comment by stemangiola** [comment]
> primary factor + additional factors

I would say factor of interest ?



> contrasts input in a similar format

I though about that, but what about (?)

```
group_1 - 1/3  * group_2 - 1/3 * group_3 - 1/3 * hroup_4
```

The parsing of arbitrary contrasts from edgeR into deseq2 is not trivial, and I don't know deseq2 enough to realise if they could be mapped 1 to 1

**Comment by mblue9** [comment]
>"
@param .formula A formula representing the desired linear model. If there is more than one factor and contrasts are not specified, they should be in the order factor of interest + additional factors
"

sounds good to me

>The parsing of arbitrary contrasts from edgeR into deseq2 is not trivial, and I don't know deseq2 enough to realise if they could be mapped 1 to 1

I don't know enough about deseq2 contrasts at this point either to be sure about that so better just keep it as you have it.

**Comment by stemangiola** [comment]
> sounds good to me

cool, I edited with parenthesis. See what you think.

**Comment by mblue9** [comment]
ok sounds good, just to check, the bit in parenthesis "(and contrasts are not specified)" means they can put the factors in any order if they specify contrasts and all the methods can handle that? e.g.

```
    test_differential_abundance(
      .formula = ~ 0 + cell + dex,
      .contrasts = c("dextrt - dexuntrt")
```
gives the same result as below for all methods

```
    test_differential_abundance(
      .formula = ~ 0 + dex + cell,
      .contrasts = c("dextrt - dexuntrt")
```

**Comment by stemangiola** [comment]
> 
> 
> ok sounds good, just to check, the bit in parenthesis "(and contrasts are not specified)" means they can put the factors in any order if they specify contrasts and all the methods can handle that? e.g.
> 
> ```
>     test_differential_abundance(
>       .formula = ~ 0 + cell + dex,
>       .contrasts = c("dextrt - dexuntrt")
> ```
> 
> gives the same result as below for all methods
> 
> ```
>     test_differential_abundance(
>       .formula = ~ 0 + dex + cell,
>       .contrasts = c("dextrt - dexuntrt")
> ```

Correct (I think, do not have proven evidence). 

The point is the sentence above makes sense when contrasts are not specified, if they are specified you directly define you factor of interest etc.. If not we assume the first covariate is your factor of interest.

**Comment by mblue9** [comment]
>Correct (I think, do not have proven evidence).

Just tested it & get error:

`Error in eval(ej, envir = levelsenv) : object 'dextrt' not found`

As I realised that this probably wouldn't work:
```
counts_scal_PCA %>%
test_differential_abundance(.formula = ~ 0 + cell + dex, .contrasts = c("dextrt - dexuntrt"))
```

as adding 0 only omits the intercept for the first factor with edgeR/limma 

So better to omit the bit about contrasts & say

"
@param .formula A formula representing the desired linear model. If there is more than one factor, they should be in the order factor of interest + additional factors
"

**Comment by stemangiola** [comment]
Hello @mblue9, should I take action about this issue? I don't want to duplicate changes if you have already. Otherwise, I will do no problem!

**Comment by mblue9** [comment]
Just pushed here https://github.com/stemangiola/tidybulk/pull/128
Also has fixes for a couple of typos I saw
