### ISSUE TITLE
limma_voom sample weighing in test_differential_abundance?

### ISSUE THREAD

**Issue by AMChalkie** [stemangiola/tidybulk#117]
Hi,

Enjoying the package! Is there a plan to include voom with sample weighting option into test_differential_abundance?

Thanks
/Alistair

**Comment by stemangiola** [comment]
Hello,

interesting question. We have to think about a clean extension of the method test_differential_abundance, to include something that only voom uses.

It would be nice to integrate it. It is not super-high priority, but we can start discussion about it.

Also it is always possible to create a pull-request if you feel you can/want to contribute.

**Comment by mblue9** [comment]
Maybe it could be added as an additional method option like the way tidybulk has the 2 edgeR options? e.g. `method=limma-voomWithQualityWeights`(altho maybe with a better shorter name)

**Comment by stemangiola** [comment]
Aaa, sure I was thinking it was requiring the input of weights but actually estimate them. In that case the approach is well modular, just adding another stream is the way to go.

Thanks for the reminder!

**Comment by stemangiola** [comment]
@AMChalkie  Pasting here the gold standard way to execute the weighted voom analysis would be of great help

**Comment by AMChalkie** [comment]
voomWithQualityWeights generally looks like this:

counts <- counts[keep,]

nf <- calcNormFactors(counts)
y<-voomWithQualityWeights(counts, design, plot=FALSE,lib.size=colSums(counts)*nf)

fit <- lmFit(y,design)
fit2 <- contrasts.fit(fit, cont.matrix)
fit2 <- eBayes(fit2)

out.dt <- data.table(topTable(fit2, n=Inf, sort.by='none'))

**Comment by mblue9** [comment]
Yes afaik it's just a straight replacement of `voom()` with `voomWithQualityWeights()`

**Comment by stemangiola** [comment]
We haven't forgot this! We have Bioconductor submission and BioC2020 as priorities. But in 15ish days we will be free to comtinue feature requests :)

**Comment by stemangiola** [comment]
Hello, the method "limma_voom_sample_weights" has been added to `test_differential_abundance`
