### ISSUE TITLE
Consistent column names for differential expression results

### ISSUE THREAD

**Issue by AMChalkie** [stemangiola/tidybulk#120]
Currently differential expression results will return different column names for what is essentially the same type of output

edgeR: logFC logCPM       F PValue   FDR
limma_voom: logFC AveExpr       t P.Value adj.P.Val     B

Is it worth making these somewhat consistent in the output? (i.e. at least PValue/P.Value => a consistent PValue)?

It would reduce fiddly downstream code changes.

**Comment by stemangiola** [comment]
On one hand this is true, but for the moment I decided to leave it to the backed algorithms to pass column names. 

The reason being that 

- we would have to take responsibility on nomenclature
- Not all methods pass the same (or same number) of statistics
- the introduction of more methods would be less scalable

There are merits in being more consistent or being more lean. Let's wait to receive a bit more feedback from the community before we make the switch. Once made it's hard to go back.

Thanks for the suggestion, and please keep make suggestions/critiques!

(I will leave this ticket open)

**Comment by mblue9** [comment]
My 2 cents is I get why it would be handy @AMChalkie, and maybe more people might request it too, but for the reasons @stemangiola said I think for the moment it's probably better to let users rename the columns if they like with e.g.`rename(PValue = P.Value, FDR = adj.P.Val) `

**Comment by AMChalkie** [comment]
It is one of those weird things that I am really surprised the community never cleaned up years ago, and now there is a bunch of old code that expects those headers which is likely why they are unlikely to change. For something like tidybulk where its a one-stop-shop there is a possibility to lead the way with consistent object types :) No expectation that it happens though.

I think for tutorials/docs it would be handy to include that rename line as a suggestion (and/or a comment) that when the method (i.e. voom/DEseq?) gives results that are different from the default.

**Comment by mblue9** [comment]
>It is one of those weird things that I am really surprised the community never cleaned up years ago, and now there is a bunch of old code that expects those headers which is likely why they are unlikely to change. For something like tidybulk where its a one-stop-shop there is a possibility to lead the way with consistent object types :) No expectation that it happens though.

It is strange I was especially surprised when I discovered edgeR and limma-voom didn't have consistent column names even though they came from the same group. So if they couldn't manage to agree maybe that indicates it'd be difficult to get a consensus. But showing people how they could make the names consistent themselves would be at least a start. 

>I think for tutorials/docs it would be handy to include that rename line as a suggestion (and/or a comment) that when the method (i.e. voom/DEseq?) gives results that are different from the default.

I agree 😄  so I just added it to the tut we're working on [here](https://github.com/stemangiola/rpharma2020_tidytranscriptomics/pull/7/commits/2c3aee1e821b473ad34966271db27828973b70d0)

**Comment by AMChalkie** [comment]
Nice one :) 

The tutorial documentation is looking good and I really like the project as a whole.

**Comment by AMChalkie** [comment]
Also AveExpr and logCPM aren't consistent either(!!) Though I assume they are the same thing. This will mess with the MA plots.

**Comment by mblue9** [comment]
Could you rename those to `AveAb` like below for the moment?
Below is from the iSEEu package they do some conversion of fields

If this is an issue for people maybe there could be a helper function called  e.g. `standardise_names` 

https://rdrr.io/bioc/iSEEu/src/R/utils_de.R

```
#' @rdname utils-de
.getAcceptablePValueFields <- function() {
    .acceptable_template("PValue", c("PValue", "p.value", "pval"))
}

#' @export
#' @rdname utils-de
.getAcceptableLogFCFields <- function() {
    .acceptable_template("LogFC", c("logFC", "LogFC"))
}

#' @export
#' @rdname utils-de
.getAcceptableAveAbFields <- function() {
    .acceptable_template("AveAb", c("AveExpr", "logCPM"))
}
```

**Comment by stemangiola** [comment]
So I see four options here

1) Always convert column names according to some nomenclature
2) Making optional conversion (default or not) with an additional argument to the test_differential_abundance function
3) Creating an utility function that does the conversion
4) Leave columns up to the backend algorithms

Personally I like 1 and 4, that is, make the call without incresing the complexity of the UI. But would be nice to have more feedback/discussion

**Comment by AMChalkie** [comment]
Another option, kind of a hybrid between 1+4:

Leave the original columns as and then create extra columns that are consistent (logFC, avgExp, PValue, FDR) that are then used in all downstream figures. Done within test_differential_abundance.

Question: Does that just make it overly messy, or is there utility in keeping the original tool output (which I think is desirable).

**Comment by stemangiola** [comment]
Hello, for the moment we keep the result columns up to the backend algorithms. In this way we keep transparency, and keep lean. If we'll receive more issues on the matter we will be happy to reopen.

Thanks for the feedback!
