### ISSUE TITLE
directionality of log2FoldChange (DESeq2) opposite to voom and edgeR

### ISSUE THREAD

**Issue by AMChalkie** [stemangiola/tidybulk#123]
Hi,

I was running all three methods on a single dataset, same formula, same contrasts and got opposite directionality for my logFC values! 

tidybulk_1.1.8

Guessing there is a missing test in the sample data: logFC for given gene in test dataset is consistent?

Code: 

counts_de.voom <- tt.aggr  %>%  identify_abundant(factor_of_interest = genotype) %>% scale_abundance() %>% keep_abundant() %>%
    test_differential_abundance(
      .formula = ~ 0 + genotype, # + cell,
      .contrasts = c("genotypeKI - genotypeWT"),
      method = "limma_voom", # edgeR_quasi_likelihood", # Alternative method. "limma_voom",
      omit_contrast_in_colnames = TRUE,
      prefix= "limma_voom."
    )

counts_de.edger <- tt.aggr  %>%  identify_abundant(factor_of_interest = genotype) %>% scale_abundance() %>% keep_abundant() %>%
    test_differential_abundance(
      .formula = ~ 0 + genotype, # + cell,
      .contrasts = c("genotypeKI - genotypeWT"),
      method = "edgeR_quasi_likelihood", # Alternative method. "limma_voom",
      omit_contrast_in_colnames = TRUE,
      prefix= "edgeR_quasi_likelihood."
    )

counts_de.DESeq2 <- tt.aggr  %>%  identify_abundant(factor_of_interest = genotype) %>% scale_abundance() %>% keep_abundant() %>%
    test_differential_abundance(
      .formula = ~ 0 + genotype, # + cell,
      .contrasts = c("genotypeKI - genotypeWT"),
      method = "DESeq2", # Alternative method. "limma_voom",
      omit_contrast_in_colnames = TRUE,
      prefix= "DESeq2."
    )

**Comment by stemangiola** [comment]
Hello @AMChalkie . We though we fixed it. Indeed the workshop material shows expected results.

Could you please execute the section

https://stemangiola.github.io/biocasia2020_tidytranscriptomics/articles/tidytranscriptomics.html#differential-expression-1

and tell us if you still see the opposite results. In this way we can understand where the issue lies.

**Comment by stemangiola** [comment]
Some notes on coding.

You don't necessarily need to replicate code. This would suffice:

```
counts_de.voom <-
   tt.aggr %>% 

   identify_abundant(factor_of_interest = genotype) %>% 

   test_differential_abundance(
      .formula = ~ 0 + genotype, # + cell,
      .contrasts = c("genotypeKI - genotypeWT"),
      method = "limma_voom", # edgeR_quasi_likelihood", # Alternative method. "limma_voom",
      omit_contrast_in_colnames = TRUE,
      prefix= "limma_voom."
   ) %>%

   test_differential_abundance(
      .formula = ~ 0 + genotype, # + cell,
.      contrasts = c("genotypeKI - genotypeWT"),
      method = "edgeR_quasi_likelihood", # Alternative method. "limma_voom",
      omit_contrast_in_colnames = TRUE,
      prefix= "edgeR_quasi_likelihood."
  ) %>%

  test_differential_abundance(
    .formula = ~ 0 + genotype, # + cell,
.    contrasts = c("genotypeKI - genotypeWT"),
    method = "DESeq2", # Alternative method. "limma_voom",
    omit_contrast_in_colnames = TRUE,
    prefix= "DESeq2."
 )

```

**Comment by AMChalkie** [comment]
Thanks for the coding note. I'm still not used to the tidy way, so much appreciated.

**Comment by stemangiola** [comment]
Hello @AMChalkie I have created a pull request. Could you please check that the respective branch leads to expected results on your side?

That would be much appreciated.

**Comment by AMChalkie** [comment]
Not yet:

tidybulk says: All methods use raw counts, 
irrespective of if scale_abundance or adjust_abundance have been calculated, 
therefore it is essential to add covariates such as batch effects (if applicable) in the formula.
Error in get_differential_transcript_abundance_deseq2(., .formula, .sample = !!.sample,  : 
  tidybulk says: for the moment, the .contrasts argument for
DESeq2 gets directly passed to DESeq2 method.
Contrasts must be a list that contains contrasts of
the form c("condition","C","B")
Called from: get_differential_transcript_abundance_deseq2(., .formula, .sample = !!.sample, 
    .transcript = !!.transcript, .abundance = !!.abundance, .contrasts = .contrasts, 
    method = method, scaling_method = scaling_method, omit_contrast_in_colnames = omit_contrast_in_colnames, 
    prefix = prefix)

**Comment by stemangiola** [comment]
Maybe I should improve this message

```
for the moment, the .contrasts argument for
DESeq2 gets directly passed to DESeq2 method.
Contrasts must be a list that contains contrasts of
the form c("condition","C","B")
```

Is not self-explanatory? Feel also free to edit it directly in the repo if you can think about something clearer for users.

**Comment by AMChalkie** [comment]
For documentation: 

for the moment, the .contrasts argument for
DESeq2 gets directly passed to DESeq2 method.
Contrasts must be a list that contains contrasts of
the form c("factorName","numeratorLevel","denominatorLevel")

I would have expected that this would work, but no...:

tt.aggr  %>%  identify_abundant(factor_of_interest = genotype) %>%
     test_differential_abundance(
         .formula = ~ 0 + genotype, 
         .contrasts = c('genotype','KI','WT'),
         method = "DESeq2", 
         omit_contrast_in_colnames = TRUE,
         prefix= "DESeq2."
     )
tidybulk says: All methods use raw counts, 
irrespective of if scale_abundance or adjust_abundance have been calculated, 
therefore it is essential to add covariates such as batch effects (if applicable) in the formula.
estimating size factors
estimating dispersions
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
fitting model and testing
Error in checkContrast(contrast, resNames) : 
  'contrast', as a character vector of length 3, should have the form:
contrast = c('factorName','numeratorLevel','denominatorLevel'),
see the manual page of ?results for more information
In addition: Warning message:
In get_differential_transcript_abundance_deseq2(., .formula, .sample = !!.sample,  :
  tidybulk says: you can omit contrasts in column names only when maximum one contrast is present
Called from: checkContrast(contrast, resNames)

Also, this is after removing the check for equals("list") as it failed here otherwise.

.contrasts %>% is.null %>% not() &
		.contrasts %>% class %>% equals("list") #%>% not()

**Comment by stemangiola** [comment]
"a list that contains contrasts"

list(c('genotype','KI','WT'))

As you can specify many contrast combinations (similarly to edgeR)

**Comment by stemangiola** [comment]
I see the other problem. Tomorrow I fix everything

**Comment by stemangiola** [comment]
Hello @AMChalkie could you please reinstall this branch and try again? I have improve error messages. Let's see if it guides you better.

**Comment by AMChalkie** [comment]
That worked just fine, excellent :) Nice work.

I would still change the error message to be:

tidybulk says: for DESeq2 the list of constrasts should be given in the form list(c("condition_column","condition1","condition2")) i.e. list(c("genotype","knockout","wildtype")).

rather than

tidybulk says: for DESeq2 the list of constrasts should be given of the form list(c("condition","C","B"))
