### ISSUE TITLE
Quiet parameter for keep_variable()

### ISSUE THREAD

**Issue by canholyavkin** [stemangiola/tidybulk#133]
The keep_variable() function prints out the following phrase by default:
`## Getting the 500 most variable genes`

While it is not important for scripting, the message stays at the R markdown document even I designate `knitr::opts_chunk$set(message = F)`

Is it possible to suppress this message?

**Comment by stemangiola** [comment]
Hello,

this message comes from edgeR, I would suggest to write to the maintainers. 

All our messages are correctly wrapped under message() for this exact reason :)

**Comment by mblue9** [comment]
@stemangiola or could it be coming from this line in tidybulk https://github.com/stemangiola/tidybulk/blob/master/R/functions.R#L2568

**Comment by stemangiola** [comment]
> 
> 
> @stemangiola or could it be coming from this line in tidybulk https://github.com/stemangiola/tidybulk/blob/master/R/functions.R#L2568

Interesting! I have to double check although in that message there is no `##` and is wrapped with the message() function which should respect the suppression.

**Comment by stemangiola** [comment]
> 
> 
> The keep_variable() function prints out the following phrase by default:
> `## Getting the 500 most variable genes`
> 
> While it is not important for scripting, the message stays at the R markdown document even I designate `knitr::opts_chunk$set(message = F)`
> 
> Is it possible to suppress this message?

@canholyavkin do you feel like try to comment the line  https://github.com/stemangiola/tidybulk/blob/master/R/functions.R#L2568 and see if that issue goes away? 

The issue is that the message() function should allow for silencing with global parameters. I am a bit puzzled.

**Comment by canholyavkin** [comment]
Sure. I'll check and write the results here.

**Comment by canholyavkin** [comment]
I commented the line at https://github.com/stemangiola/tidybulk/blob/master/R/functions.R#L2568.

When I set `knitr::opts_chunk$set(message = F)` or `knitr::opts_chunk$set(message = T)` the message of `## Getting the 500 most variable genes` is gone now.

**Comment by stemangiola** [comment]
> 
> 
> I commented the line at https://github.com/stemangiola/tidybulk/blob/master/R/functions.R#L2568.
> 
> When I set `knitr::opts_chunk$set(message = F)` or `knitr::opts_chunk$set(message = T)` the message of `## Getting the 500 most variable genes` is gone now.

Alright, @mblue9 is right as usual. XD

Thanks for doing it. The standard way to suppress messages is to wrap a command in `suppressMessages()`. That should work. I am not sure why knitr does not gives the same result.

Our approach is correct (using message() to print messages), unless I am missing something big.

**Comment by canholyavkin** [comment]
Thank you. :) `suppressMessages()` is worked. Have I nice day.
