### ISSUE TITLE
pass ... ellipse argument to test_differential_abundance

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidybulk#136]
For example to get plot=TRUE from voom

**Comment by tuhulab** [comment]
Hi @stemangiola, a similar question. How to pass "parallel = TRUE" to DESeq2?

**Comment by stemangiola** [comment]
Hello, can you try with the linked branch?

**Comment by stemangiola** [comment]
The ellipse in test_dofferential_abundance should take any argument assed to deseq2

**Comment by stemangiola** [comment]
I close for lack of activity, if you could confirm whether it worked would be amazing for future development
