### ISSUE TITLE
ERROR; return code from pthread_create() is 22

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidybulk#145]
Hello @mblue9,

I tag you in case you have an idea of how to proceed.

For the pull request https://github.com/stemangiola/tidybulk/pull/139 we have this error

```
ERROR; return code from pthread_create() is 22
```

Due to the loading of preprocessCore for Cibersort, this happens only in github actions.

I found a possible solution from https://support.bioconductor.org/p/122925/

```
git clone https://github.com/bmbolstad/preprocessCore.git
cd preprocessCore/
R CMD INSTALL --configure-args="--disable-threading"  .
```
Do you know how to install preprocesscore with this procedure in github actions rather than the normal dependency manager?

**Comment by mblue9** [comment]
That error was fixed here https://github.com/stemangiola/tidybulk/pull/150/commits
