### ISSUE TITLE
Survival Analysis

### ISSUE THREAD

**Issue by france-hub** [stemangiola/tidybulk#155]
Hello Stefano, 

Thank you for the great packages. 
I've noticed that with tidybulk you can perform a survival analysis in terms of relationships of different subpopulations with survival. 

I was wondering if it's possible to use your package to estimate Kaplan-Meier survival curves. What I am trying to do is understanding if the expression of one gene or even a gene module (defined as a categorical variable: low, mid, high) predict survival. Something similar to what some tools (eg gepia2) allow to do for TCGA data. 

Thank you

Best,
Francesco

**Comment by stemangiola** [comment]
Ciao Francesco,

puoi installare la versione dev

devtools::install_github("stemangiola/tidybulk@dev")

e usare la funzione test_stratification_cellularity, per esempio

```r
you_data %>%
test_stratification_cellularity(
	survival::Surv(days, dead) ~ .,
         ...
)
```

Il data frame che ricevi contiene una colonna con i grafici.

**Comment by france-hub** [comment]
Grazie mille!

Ancora complimenti per i pacchetti.

Buona giornata
