### ISSUE TITLE
test_gene_enrichment error: object '.transcript' not found

### ISSUE THREAD

**Issue by mblue9** [stemangiola/tidybulk#166]
Heya, I was trying to include a small example of using tidybulk's test_gene_enrichment in a tutorial but I can't get it to run. I'm getting the error `Error in enquo(.transcript) : object '.transcript' not found`. 

The example in the function here https://github.com/stemangiola/tidybulk/blob/master/R/methods.R#L2807-L2822 gives the same error e.g. 
```
# From tidybulk example
df_entrez = symbol_to_entrez(tidybulk::counts_mini, .transcript = transcript, .sample = sample)
df_entrez = aggregate_duplicates(df_entrez, aggregation_function = sum, .sample = sample, .transcript = entrez, .abundance = count)

library(EGSEA)
test_gene_enrichment(
			df_entrez,
			~ condition,
			.sample = sample,
			.entrez = entrez,
			.abundance = count,
       method = c("roast" , "safe", "gage"  ,  "padog" , "globaltest", "ora" ),
			species="human",
			cores = 2
		)
```

Is it something to do with .transcript not being an argument (.entrez is instead) but then there's a check for .transcript here ?https://github.com/stemangiola/tidybulk/blob/852d996ac89ec7f342cb17bf226a40974e5ce899/R/methods.R#L2863

**Comment by stemangiola** [comment]
Oops!

fixed here

https://github.com/stemangiola/tidybulk/commit/5c3622bd289a598cc86a1c13665ca5902b4abe96
