### ISSUE TITLE
Fixing github action

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidybulk#168]
Hello @mblue9 I was wondering if you had time to give an hand with fixing the github actions for Master.

The error is due to the use of tidySE in the vignette, that is only available in Bioc 3_13.

**Comment by stemangiola** [comment]
I tried here 

https://github.com/stemangiola/tidybulk/pull/163

without success.

After that I will be able to check and merge 5 branches! :)

**Comment by mblue9** [comment]
The error is not due to the action as far as I can see as I get that error locally without actions when running the vignette using R 4.1, Bioc 3.13 and tidySE 1.1.3 e.g. when I was testing this PR https://github.com/stemangiola/tidybulk/pull/169
