### ISSUE TITLE
Use feature instead of transcript

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidybulk#182]
Since tidy* packages were converted to feature vocabulary, at some point we should adapt tidybulk too. @mblue9 concerns?

**Comment by mblue9** [comment]
>Since tidy* packages were converted to feature vocabulary, at some point we should adapt tidybulk too. @mblue9 concerns?

Nope no concerns, sounds good. Some people consider transcripts==isoforms so using feature could also eliminate any potential for confusion there.
