### ISSUE TITLE
Use data.table in aggregate_duplicate() for huge data frames

### ISSUE THREAD

**Issue by RAGG3D** [stemangiola/tidybulk#186]
Hi,

I've found applying aggregate_duplicate() to huge data frames (eg. TCGA-BRCA)could be very slow.
So I tried data.table and the code is:

 as_tibble(
    data.table::setDT(
    *data frame*
    )[, list(abundance = sum(*abundance*)), by = c("*sample*", "*transcript*")]) %>%  *#Sum the raw_counts of duplicated rows*
    tidybulk::scale_abundance(.sample = *sample*, .abundance = *abundance*, .transcript = *transcript*)

Then this step takes less than 1 min.
Maybe data.table should be added into this function?

Many thanks!

**Comment by stemangiola** [comment]
Thanks, Yuhan. Do you want to try to create a pull request with code changes?

That would be a good experience for you and would make you a collaborator of this repository :)

**Comment by mblue9** [comment]
I also encountered this today. Also happened to be using TCGA BRCA and aggregate_duplicates was the slowest step in the workflow. Having a speedier option would be great!

**Comment by stemangiola** [comment]
I have designed an alternative, because data.table dependencies create problems for some reason.
