### ISSUE TITLE
Confused on TidyBulk's desired format

### ISSUE THREAD

**Issue by JohnHadish** [stemangiola/tidybulk#187]
Hello tidybulk team. 

I am confused about the tidybulk format. I have found some discrepancies within your documentation, which I suspect have been caused by updates. Here are all the different formats I have found:

**1)** Error message of the `%>% tidybulk()` command when I am attempting to use a tibble with tidybulk:
```
Error in validation.default(.data, !!.sample, !!.transcript, !!.abundance,  : 
  tidybulk says: One or more columns .sample .transcript or .abundance are missing from your data frame.
```

**2)** Documentation which ships with Tidybulk Bioconductor version : 

![image](https://user-images.githubusercontent.com/35115540/120713287-89ae0400-c476-11eb-8691-b9e40f6808e5.png)

**3)** Image on TidyBulk [github](https://github.com/stemangiola/tidybulk)  of example workflow:
![image](https://user-images.githubusercontent.com/35115540/120713744-2ffa0980-c477-11eb-82f7-90cb08dbd85b.png)

**4)** Documentation in GitHub `README.md`
```
## # A tibble abstraction: 408,624 x 8
##    transcript sample     count Cell.type time  condition batch factor_of_intere…
```

---
Within these 4, we see 4 different name combinations:

| Format 1 | Column 1 Name | Column 2 Name | Column 3 Name |
| --- | --- | --- | ---|
| 1 | sample | transcript | abundance|
| 2 | sample | transcript | count |
| 3 | transcript | sample | count**s** |
| 4 | transcript | sample | count |

**bolded text** to indicate plural words

---

I have come across this issue, as I am attempting to convert a Gene Expression Matrix in this form:
```
name sample_1   sample_2   sample_3
gene1   2   2   4 
gene2   4   3   5
gene3   6   2   2
```
to be used with the Tidybulk universe. 

I currently have it formatted as a tidy tibble:
![image](https://user-images.githubusercontent.com/35115540/120714382-fb3a8200-c477-11eb-878b-a60696f929b4.png)

What would you recommend is a good way for me to use my tibble with tidyBulk?

Cheers,
John

My System Information:
- Ubuntu 20.04 
- R: 4.1.0
- RStudio: 1.4.1717
- tidybulk - 1.4.0 (from Bioconductor)

**Comment by stemangiola** [comment]
Hello John,

thanks for bringing these things up. We have improved the documentation and error message for consistency. Please install devtools::install_github("stemangiola/tidybulk@fix-docs-terminology"). And let us know if the experience is better.

> Error message of the `%>% tidybulk()` command when I am attempting to use a tibble with tidybulk:

The error message (now improved) could be confusing to some. It just means that you have to fill the arguments .sample .transcript and .abundance with the respective column names.



> **2)** Documentation which ships with Tidybulk Bioconductor version :

That has changed. Please tell us what you think.

> What would you recommend is a good way for me to use my tibble with tidyBulk?

```r
your_data_frame %>%
    tidybulk(.sample = sample, .transcript = transcript, .abundance = abundance)
```

From a tidy tibble you can apply each function in the tidybulk framework also without ever calling tidybulk(...) You just would have to specify every time `.sample = sample, .transcript = transcript, .abundance = abundance`

**Comment by JohnHadish** [comment]
That looks great, thank you!
