### ISSUE TITLE
Arguement "minimum_proportion" of the function "keep_abundant()" appears to not do anything

### ISSUE THREAD

**Issue by JohnHadish** [stemangiola/tidybulk#192]
Minimum working Example:

```
library(tidyverse)
library(tidySummarizedExperiment)
library(airway)
library(tidybulk)
data(airway)

airway %>%
  keep_abundant(minimum_counts = 100000, minimum_proportion = 0) %>%
  print(n = 100)

airway %>%
  keep_abundant(minimum_counts = 100000, minimum_proportion = 1) %>%
  print(n = 100)
```

Notice that both produce the same result. Also note that there are values under 100000.
I am guessing that it is hardcoded at `.7`

**My System Information:**

Ubuntu 20.04
R: 4.1.0
RStudio: 1.4.1717
tidybulk - "stemangiola/tidybulk@fix-docs-terminology"

**Comment by stemangiola** [comment]
You are right.

However, the parameter is passed to `edgeR::filterByExpr` (as specified in the documentation), and proportion does not affect that function either with the test dataset.

Could you please try `edgeR::filterByExpr` directly with your dataset, and see if you have some change.

If not, it would be a nice issue to raise with the edgeR team.

**Comment by stemangiola** [comment]
Hello @JohnHadish, any news? can I close?
