### ISSUE TITLE
Using contrasts instead of .contrasts is silently ignored

### ISSUE THREAD

**Issue by mblue9** [stemangiola/tidybulk#208]
Just had a user contact me about a weird result they had, turned out it was because they had specified `contrasts=` without the `.` in `test_differential_abundance` and so the contrast was silently ignored. Wondering if you think it would be worth adding a warning or error message to alert the user if they accidentally use `contrasts` instead of `.contrasts`?

**Comment by stemangiola** [comment]
Yes, I'm not sure with contrast has . before usually I try to reserve that for the column symbols, not strings.

Feel free to add the warning, and if you think is worth we could think about deprecation of the dot? (we have few argument deprecations, it's quite clean). But yes warning could be worth it.

**Comment by stemangiola** [comment]
@mblue9 solved in the linked pull requests, if you want to test would be amazing
