### ISSUE TITLE
Retain count_scaled in as_SummarizedExperiment()

### ISSUE THREAD

**Issue by jianwu1** [stemangiola/tidybulk#212]
![image](https://user-images.githubusercontent.com/62498686/133884335-4fbdf522-2514-449d-b114-cf93b40289b7.png)

tidybulk version: devtools::install_github("stemangiola/tidybulk@for-jian", force = TRUE)

Test input data can be found in this link:
[https://drive.google.com/file/d/1txnGl6mq6sy2fHMsRxzbftBC0iwQj-g8/view?usp=sharing](url)

**Comment by stemangiola** [comment]
This was solved with the new versions of tidybulk and SummarizedExperiment soon to be merged.

I hope your PhD is going well.

**Comment by jianwu1** [comment]
@stemangiola 
Hi Stefano,

Thanks! It's going ok. Hope you have a wonderful trip to Italy!

We just got our scRNAseq data. I'm trying to convert the bcl files into fastq files but found that the SampleSheet.csv file: 
(for example: [https://github.com/YichaoOU/HemTools/blob/master/docs/gallery/SampleSheet.csv](url) )
that contains information such as the adapter, flow cell lane, etc are missing. Can I ask if I should ask WEHI sequencing people for this file or if we could create this file myself in order to use bcl2fastq?

Here is the data folder given by WEHI sequencing staff:
<img width="941" alt="Screen Shot 2022-06-27 at 10 15 04 am" src="https://user-images.githubusercontent.com/62498686/175856456-44179ffb-9dd9-42bf-b552-53ae0874be41.png">


Kind regards,

Jian

**Comment by stemangiola** [comment]
Hello Jian,

better we bring this conversation to email, as it is not really about tidybulk.

My answer would be, to contact the sequencing facility and bioinformatic service at WEHI and ask them, as it is something that involved data managing, not really data analysis.
