### ISSUE TITLE
create_tt_from_bam_sam_bulk function recuires org.Hs database and is therefore incompatible with other organisms

### ISSUE THREAD

**Issue by richardstoeckl** [stemangiola/tidybulk#221]
Hello and thank you for your great package!

I want to use this package with data from Arbabidopsis thaliana.
Sadly, when I try to use the "tidybulk_SAM_BAM()" wrapper function I get the error  message 
`Error when evaluating the argument 'x' for the function 'mapIds': there is no package called ‘org.Hs.eg.db’` 
and after I install  the "org.Hs.eg.db", I get the Error 
`Error in .testForValidKeys(x, keys, keytype, fks) : 
  None of the keys entered are valid keys for 'ENTREZID'. Please use the keys method to see a listing of valid arguments.`

So I had a look at the sourcecode and if I understand it correctly, the function "create_tt_from_bam_sam_bulk()" calls the function "AnnotationDbi::mapIds()" when a external annotation file is specified (which is required since Arabidopsis is not provided with the subread package) with the hard-coded default parameter set to  "org.Hs.eg.db", which is obviously not for every organism.

Is there a way to remove this dependency or make it customizable for other organisms? 

Thanks,
Richard

**Comment by stemangiola** [comment]
Hello @richardstoeckl, few weeks become many months (sorry about that).

Would you like to try again? The branch where I fixed it is 

allow-mapping-to-other-genomes
