### ISSUE TITLE
pivot_sample and pivot_transcript convert .sample and .feature to sample and feature

### ISSUE THREAD

**Issue by mblue9** [stemangiola/tidybulk#222]
Heya not a big deal just flagging this as I noticed it in the workshop [here](https://tidytranscriptomics-workshops.github.io/rpharma2021_tidytranscriptomics/articles/tidytranscriptomics.html#exploratory-analyses-1), the `.sample` and `.feature` columns get changed to `sample` and `feature` when those two functions are run. So if you try to use .sample to select column (which is what's being used up to that point in tutorial) you get error.

Thanks for submitting an issue.

Please add the following information to the issue

1. Describe the issue/bug
2. Print out the input dataset immediately before the bug occurs
3. Paste the code immediately leading to the bug
4. Print out of the output, if any
5. Print out of the complete error/warning message, if any
6. sessionInfo()

Thanks!

**Comment by stemangiola** [comment]
Fixed in the attached pull request

**Comment by mblue9** [comment]
Great 👍
