### ISSUE TITLE
DEG Analysis Between Single Group with Multiple Groups

### ISSUE THREAD

**Issue by canholyavkin** [stemangiola/tidybulk#245]
Let's say that we have 6 samples split into 3 groups.
Sample_1 ~ Group_A
Sample_2 ~ Group_A
Sample_3 ~ Group_B
Sample_4 ~ Group_B
Sample_5 ~ Group_C
Sample_6 ~ Group_C

If I want to compare A and B, I use the following code:

```
counts_de <- counts_scaled %>%
  identify_abundant(factor_of_interest = group) %>%
  test_differential_abundance(
    ~ 0 + group,
    .contrasts = c("groupA - groupB"),
    action="get"
  )
```

What should I use if I want to compare A with B and C together? (eg. compare Sample 1 and 2 with 3-4-5-6)

**Comment by stemangiola** [comment]
```.contrasts = c(groupA - 1/2*groupC - 1/2* groupC))```

**Comment by canholyavkin** [comment]
Thank you. I think you mean `.contrasts = c(groupA - 1/2*groupB - 1/2* groupC))` right?

In this case, it will compare A with B+C, is it correct?

**Comment by stemangiola** [comment]
```
.contrasts = c("groupA - 1/2*groupB - 1/2* groupC)")
```

yes this will compare A with the mean of the means of B and C

**Comment by canholyavkin** [comment]
Thanks. What if I want to compare the mean of the means of B and C with A. In other words, how should I write if I want to use groupA as a control?

**Comment by stemangiola** [comment]
```r
.contrasts = c("1/2*groupB + 1/2* groupC - groupA")
```

Never seen this approach however. 

I should point out that the contrast are exactly the same as for edgeR. So you can find a lot of documentation online on the edgeR contrasts. Tidy bulk it is just a nice wrapper around edgeR and many other algorithms

**Comment by canholyavkin** [comment]
In edgeR, makeContrasts is used for creating a contrast table. Can I use the output of makeContrasts function as a .contrast parameter in tidybulk? Is it compatible? 

Or are they any other notation that I can use?

Such as:

```
.contrasts = makeContrasts((treatmentCTL+treatmentIII)/2-(treatmentI+treatmentII)/2, 
  levels=colnames(design))
```
