### ISSUE TITLE
github actions give preflight error for the whole tidy stack

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidybulk#259]
Hello @mblue9, I hope you are doing amazing at your new position. If you have some spare energy ;) could you have an expert look to the errors that have emerged for the whole tidy Stack?

We should have a chat one of these days..

**Comment by mblue9** [comment]
Hi yes, I've had a quick look, it's this error reported here https://github.com/r-lib/actions/issues/639. 

I've made a PR to fix here https://github.com/stemangiola/tidybulk/pull/260
