### ISSUE TITLE
Fix spelling on analise_gene_enrichment

### ISSUE THREAD

**Issue by bferan** [stemangiola/tidybulk#26]
analise -> analyse (or analyze if American spelling is mandated)
Perhaps test_gene_enrichment would be a better name as it fits with test_differential_abundance.

**Comment by stemangiola** [comment]
Good point. I was going for the Italian spelling.

I ended up using test. Shorter and more consistent (although the operation is commonly called gene enrichment analysis).

Thanks for the suggestion.
