### ISSUE TITLE
ERROR; return code from pthread_create() is 22

### ISSUE THREAD

**Issue by indapa** [stemangiola/tidybulk#261]
I am trying to run the function deconvolve_cellularity on my data and am getting this error:
```

tb_counts  %>% 
  deconvolve_cellularity(prefix="cibersort_",cores=1)
```
But then get this error:

```
Error in normalize.quantiles(Y) :
ERROR; return code from pthread_create() is 22
```

It seems this was the same error described in this issue, but the PR that fixed it was merged last year. 
https://github.com/stemangiola/tidybulk/issues/145

Looking at the traceback, it seems it's trying to install cibersort, since it wasn't previously installed already. Maybe something is going awry here? 

`when(., method %>% tolower %>% equals("cibersort") ~ {
if (find.package("class", quiet = TRUE) %>% length %>% equals(0)) {
message("tidybulk says: Installing class needed for Cibersort")
install.packages("class", repos = "https://cloud.r-project.org", ...`

**Comment by indapa** [comment]
Do I need to to get a license for cibersort?  I tried installing on it's own, but it seems my version of R is not compatible
```
install.packages("cibersort")
Installing package into ‘/home/aindap/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘cibersort’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

**Comment by stemangiola** [comment]
Cibersort does not need installation. Looks like you have problems installing `install.packages("class")` Try manually.

**Comment by indapa** [comment]
I figured it out. I tried manually to run this command:

BiocManager::install("preprocessCore", configure.args="--disable-threading")

After re-started my R session, it seems to have worked
