### ISSUE TITLE
Design and contrasts for tidybulk test differential abundance function 

### ISSUE THREAD

**Issue by adityamahadevaniyer** [stemangiola/tidybulk#264]
I have 12 samples - 3 Controls, 3 T1 , 3 T2 and 3 T3. I am interested in looking at genes that are different between controls and treatment. Also I would like to obtain DE genes that are different between control average and treatment average for which I had provided the contrast above that I want from the analysis (T1 + T2 + T3)/3 - Controls.
I am unable to input such contrasts in the test_differential_abundance function under the contrasts argument.
Can you suggest the design and contrasts arguement for looking at

control vs treatments and
controls average versus treatment average.

`counts_DE = counts_scal_PCA %>% test_differential_abundance(~treatment, method = “”)

resultNames(attr(counts_de, “internals”)$DESeq2
`
gives me intercept, treatment_C_v_T1, treatment_C_vs_T2, treatment_C_vs_T3 
So I can paste any of the above options in the contrasts argument to extract relevant comparisons. 
DESeq2 requires contrasts argument in the form of a list whereas limma and edgeR need a vector format. 

counts_DE = counts_scal_PCA %>% test_differential_abundance(~treatment, method = “”)

I know how to extract results for pairwise comparisons but dont know how to input a formula / contrasts for extracting mean of controls versus mean of treatments . 

I referred this publication https://f1000research.com/articles/9-1444 (refer Control versus treatment average
section of the paper)

**Comment by stemangiola** [comment]
Is the reply here helpful?

https://support.bioconductor.org/p/9149049/#9149050

otherwise I can elaborate further.

**Comment by adityamahadevaniyer** [comment]
Thank you. Useful comment. 

Will this work?

`test_differential_abundance( ~treatment, method = “”,
contrast = (“treatmentT1 + treatmentT2 + treatmentT3)/3 - treatmentControls")`
will work for edgeR and limma-voom right. 

will 
`test_differential_abundance (~treatment, method = “DESeq2”,
contrast = list (c(“ treatmentT1 + treatmentT2 + treatmentT3)/3 - treatmentControls”)`
work for DESeq2
Am I right?

**Comment by stemangiola** [comment]
you are missing a c() for the first command.

Please try and let me know. Also this command depend on the column names of your dataset (similarly to model.matrix command)

**Comment by adityamahadevaniyer** [comment]
Got it . Thank you. I will try this first thing tomorrow and let you if this works. I will also ensure the column names are ok & matching the ones specified in the function.

**Comment by adityamahadevaniyer** [comment]
I tried the following code 
`counts %>% test_differential_abundance( ~ , method = “DESeq2”, contrasts = list (c(-1, 1/3, 1/3, 1/3)), omit_contrast_in_colnames = TRUE`

No errors while running the DESeq2 codeBut when I check number of DE genes , I get 43 Up and 15100 odd genes Downregulated. That seems odd. Right?

I used the following for edgeR/ limma voom 
`counts %>% test_differential_abundance( ~ , method = “DESeq2”, contrasts = list (c(-1, 1/3, 1/3, 1/3)), omit_contrast_in_colnames = TRUE`

I get the following warnings while running edgeR/voom  (refer the picture)

Are there issues related to default edgeR in tidybulk? https://support.bioconductor.org/p/9147697/

**Comment by adityamahadevaniyer** [comment]
Update for the DESeq2. I tried excluding the intercept in the formula by specifying ~ 0 + treatment . That seem to work! Yet to figure something out for edgeR/voom

**Comment by stemangiola** [comment]
> I used the following for edgeR/ limma voom `counts %>% test_differential_abundance( ~ , method = “”, contrasts = c(-1, 1/3, 1/3, 1/3), omit_contrast_in_colnames = TRUE)`

couple of points, 

- always specify a method, not "".
- Please see documentation ?test_differential_abundance on how to set contrasts for edgeR and voom. Please execute the examples in the documentation first.

**Comment by adityamahadevaniyer** [comment]
Thank you. I am working on a different computer. so I am manually typing the commands and the output here. It’s difficult to type the entire method , so I obviously change the method argument and take care of the syntax when I try the command on my work PC. 
The above command for edgeR/limma generated the warnings as shown in the picture above. Anyways thank you for the help.

**Comment by stemangiola** [comment]
Close for inactivity
