### ISSUE TITLE
limma:MakeContrasts integration issues

### ISSUE THREAD

**Issue by aodainic7** [stemangiola/tidybulk#309]
Hello Stefano,
in the pipeline you can use contrasts for the test_differential_abundance() to extract the comparison you are interested in. When using a formula with interaction (e.g. treatment*genotype), you create columns with colon (treatment:genotype) and limma::MakeContrasts does not accept it. If you manually modify the design matrix by exchanging : with _ the function works.
Cheers,
Alex

**Comment by stemangiola** [comment]
@aodainic7 test the branch #311

**Comment by aodainic7** [comment]
fixed
