### ISSUE TITLE
Auto-generated materials and methods?

### ISSUE THREAD

**Issue by AMChalkie** [stemangiola/tidybulk#36]
Firstly, very nice tool (and talk). 

It would be interesting to be able to create a methods text, from the resulting tibble. I imagine a case where a tibble is published/shared, and checking what was done to create it. It would also be a way of making clear the methods under the hood, and could provide citation information at the same time.

**Comment by stemangiola** [comment]
Thanks!

That's an interesting idea. Several information about algorithms and parameters are stored in attributes, and potentially all of the could be; for then been used for this.

I will keep the issue open and keep in mind for development. Of course any contribution is welcome and included in the upcoming publication!

**Comment by stemangiola** [comment]
Happy to announce that now you have automatic bibliography creation from every tidybulk tibble.

Please read readme.

Thanks for the suggestion.
