### ISSUE TITLE
test_gene_enrichment: No group or design set 

### ISSUE THREAD

**Issue by mblue9** [stemangiola/tidybulk#41]
As discussed recording here as issue: 
I tried this below with tidybulk dev, it ran but I got this message saying “No group or design set. Assuming all samples belong to one group” but they’re not all from the same group, so does it need to be given a group or design matrix or is the .formula meant to handle that?

readRDS("ent.rds") %>%
       filter(entrez %>% is.na %>% `!`) %>%
       test_gene_enrichment(
              .formula = ~ 0 + dex + cell,
              .sample = sample,
              .entrez = entrez,
              .abundance = count,
              .contrasts = c("dextrt - dexuntrt"),
              species = "human",
              cores = 4
       )

tidybulk says: The design column names are "dextrt, dexuntrt, cellN061011, cellN080611, cellN61311"
No group or design set. Assuming all samples belong to one group.

**Comment by stemangiola** [comment]
I have to improve the message. This comes from filtering. It is not so obvious in the presence of contrasts how to chose programmatically the factor of interest (column). But I will write the code to solve this scenario.

**Comment by mblue9** [comment]
I don't get this message any more. Can close issue?
