### ISSUE TITLE
 test_differential_abundance: edgeR LRT or QLF?

### ISSUE THREAD

**Issue by mblue9** [stemangiola/tidybulk#42]
Could you specify which edgeR testing method is being used in the `test_differential_abundance` help, is it the likelihood ratio test (LRT) or the quasi-likelihood F-test (QLF)?

e.g. from the edgeR user guide: https://www.bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf

> 1.4 Quick start
edgeR offers many variants on analyses. The glm approach is more popular than the classic approach as it offers great flexibilities. There are two testing methods under the glm
framework: likelihood ratio tests and quasi-likelihood F-tests. The quasi-likelihood method
is highly recommended for differential expression analyses of bulk RNA-seq data as it gives
stricter error rate control by accounting for the uncertainty in dispersion estimation. The
likelihood ratio test can be useful in some special cases such as single cell RNA-seq and
datasets with no replicates. The details of these methods are described in Chapter 2.

>A typical edgeR analysis might look like the following. Here we assume there are four RNASeq libraries in two groups, and the counts are stored in a tab-delimited text file, with gene
symbols in a column called Symbol.

> x <- read.delim("TableOfCounts.txt",row.names="Symbol")
> group <- factor(c(1,1,2,2))
> y <- DGEList(counts=x,group=group)
> keep <- filterByExpr(y)
> y <- y[keep,,keep.lib.sizes=FALSE]
> y <- calcNormFactors(y)
> design <- model.matrix(~group)
> y <- estimateDisp(y,design)

To perform quasi-likelihood F-tests:
> fit <- glmQLFit(y,design)
> qlf <- glmQLFTest(fit,coef=2)
> topTags(qlf)

To perform likelihood ratio tests:
> fit <- glmFit(y,design)
> lrt <- glmLRT(fit,coef=2)
> topTags(lrt)

**Comment by stemangiola** [comment]
tidybulk now uses glmLRT (let me know whether this only default is not generally enough)

```
.x %>%
				edgeR::glmLRT(coef = 2, contrast = my_contrasts) %>%
				edgeR::topTags(n = 999999) %$%
				table %>%
				as_tibble(rownames = quo_name(.transcript))
```

I will add to the documentation. If you would like to contribute also feel free to do so!

**Comment by stemangiola** [comment]
Actually i will add both methods

**Comment by mblue9** [comment]
Great! I think that's a good idea.
What do you think about making QRT method the default instead of LRT? 
As that's the 'highly recommended' method for bulk RNA-seq in the edgeR user guide (extract posted above).

**Comment by stemangiola** [comment]
done, create the pull request.

I invited you as collaborator, in case you wanted to visualize and comment the changes as reviewer (you don't have to).

in brief now the pipeline is
```
edgeR::DGEList(counts = .) %>%
		edgeR::calcNormFactors(method = scaling_method) %>%
		edgeR::estimateGLMCommonDisp(design) %>%
		edgeR::estimateGLMTagwiseDisp(design) %>%
[...]
	# select method
		when(
			method == "edgeR_likelihood_ratio" ~ (.) %>% edgeR::glmFit(design),
			method == "edgeR_quasi_likelihood" ~ (.) %>% edgeR::glmQLFit(design)
		)
[...]
	# select method
		when(
			method == "edgeR_likelihood_ratio" ~ (.) %>% edgeR::glmLRT(coef = 2, contrast = my_contrasts) ,
			method == "edgeR_quasi_likelihood" ~ (.) %>% edgeR::glmQLFTest(coef = 2, contrast = my_contrasts) 
	)	%>%
```

**Comment by stemangiola** [comment]
Great. I will merge in dev in couple of days if you don't have concerns.

**Comment by stemangiola** [comment]
I have to apply to SummarizeExperiment as well and make unit tests

**Comment by stemangiola** [comment]
Hello @mblue9,

I have noticed that with the default method **edgeR_quasi_likelihood** I get really few differential abundant transcripts **(n=1)**, despite this good clustering

![image](https://user-images.githubusercontent.com/7232890/84558081-7987ab00-ad73-11ea-833d-748618e4cca6.png)

While the mthod **edgeR_likelihood_ratio** I obtain many more **(n=76)**

**Comment by mblue9** [comment]
I think it's expected to get less genes with QLF as it's less liberal than LRT, better at controlling Type I error e.g. see here: https://support.bioconductor.org/p/68629/
I think the issue is that while your samples separate into the 2 groups on Dim 2 they don't on Dim 1. Do you know what might be causing the Dim 1 variation?

You could maybe compare to PCA and get the %variance for the PCs to see what % variance is explained by the PC separating the 2 groups (is it low) e.g. like here http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#principal-component-plot-of-the-samples

**Comment by stemangiola** [comment]
True. Thanks.
