### ISSUE TITLE
test_differential_abundance: misleading warning with multiple factors?

### ISSUE THREAD

**Issue by mblue9** [stemangiola/tidybulk#43]
I think this warning might be misleading, as there are more than 2 reps per primary factor (trt vs untrt) I think the secondary factor might be confusing the function? and I don't get any warning with edgeR on it's own (running it with a similar design outside tidybulk)

```counts_de <- counts_scal_MDS %>%
test_differential_abundance(
.formula = ~ 0 + dex + cell,
.contrasts = c("dextrt - dexuntrt"))```

tidybulk says: The design column names are "dextrt, dexuntrt, cellN061011, cellN080611, cellN61311"
Joining, by = "transcript"
tidybulk says: to access the raw results (glmFit) do `attr(..., "internals")$edgeR`
Joining, by = c("transcript", "lowly_abundant")
Warning message:
In get_differential_transcript_abundance_bulk(.data, .formula, .sample = !!.sample,  :
  tidybulk says: You have less than two replicated for each factorial condition

**Comment by mblue9** [comment]
Was just thinking, could you let the package that's doing the test handle this, e.g. let edgeR/limma/deseq2 complain if it doesn't have enough reps

**Comment by stemangiola** [comment]
So the warning gets thrown when for each factorial combination we have less than 2 replicated (factor of interest + other covariates).

It;s true that is not alwys bad, but the extreme cases when edgeR fails, throws a dab error, that is not understandable.

I could leave edgeR do it's job, although I wasted so much time when that happen understanding that there was some bug in formula or something. Let me think about this. The first thing I can do is to transform the warning in message.

**Comment by stemangiola** [comment]
Now it says 

message("tidybulk says: You have less than two replicated for each factorial combination")

I will leave it like this, and we stay alert and see if it's still annoying. Feel free to reopen and comment further in the future.

**Comment by mblue9** [comment]
This still triggers the message with the airway dataset. I also tested it with another commonly used example dataset (pasilla), and get the message again with this code below, which is a common design e.g. used [here](http://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html) ):
```
counts_de_pasilla <- pasilla %>%
    mutate(type=str_replace(type, "-", "_")) %>%
    test_differential_abundance(
        .sample=sample,
        .transcript=symbol,
        .abundance=`count normalised adjusted`,
        .formula = ~ 0 + condition + type,
        .contrasts = c("conditiontreated - conditionuntreated"))
```
I'm concerned that this message will cause more confusion than what it will save, especially for people new to R/RNA-seq, making them think there's something wrong. 

What was the design you had where this was an issue? As wondering if there's a way to be more precise with when to trigger the message e.g. is it possible to catch the error from edgeR and then give this message as helpful info for how to undertand the error and fix?

**Comment by mblue9** [comment]
Actually I don't get the error now with tidybulk dev & workshop dataset so think you can ignore,  I just get this other kind of odd message about picking new name:
```Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.
Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.```

**Comment by mblue9** [comment]
This is what I get with tidybulk 1.0.1 with that pasilla code above:

>Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.
Storing counts in `nn`, as `n` already present in input
ℹ Use `name = "new_name"` to pick a new name.
 Error in Summary.factor(c(1L, 1L, 2L, 2L), na.rm = FALSE) : 
  ‘min’ not meaningful for factors

**Comment by mblue9** [comment]
Just tested with tidybulk 1.1.2 and I don't get the nn message or the `min not meaningful` error anymore (great!) but I do get that message `tidybulk says: Just so you know. You have less than two replicated for each factorial combination` with both airway and pasilla datasets.
I discussed this with a statistician colleague and he also thinks it's not a good idea to give this message if the tool (edgeR) doesn't give it. I really think you should remove it or only output in response to the error you found. Is it possible to catch the edgeR error and then output this?

**Comment by stemangiola** [comment]
Oki doki!
