### ISSUE TITLE
Should filterByExpr be added into some functions help documentation?

### ISSUE THREAD

**Issue by mblue9** [stemangiola/tidybulk#44]
Do `keep_abundant` and `test_differential_abundance` use edgeR's `filterByExpr`? 

I thought so from what we discussed in the past but maybe I'm wrong? 

As here I've said filterByExpr is used 
https://stemangiola.github.io/bioc_2020_tidytranscriptomics/articles/tidytranscriptomics.html#filtering-lowly-expressed-genes

But there's no mention of it in the help for `keep_abundant` and `test_differential_abundance`.

Could you let me know if we should rephrase that or am happy to try help with the function documentation if this should be added.

**Comment by stemangiola** [comment]
Definitely, the documentation gets work intensive with such big infrastructure.

`keep_abundant` uses `filterByExpr,` and `test_differential_abundance` uses `keep_abundant` 

If you want to help would be amazing! :) Feel free to contribute with whatever you think is right.

**Comment by mblue9** [comment]
Ok :) If I want to suggest a change, just to doublecheck, do I make a branch of the tidybulk _dev_ branch?

**Comment by stemangiola** [comment]
Yes, create a branch for the change, do all your commits, and pull do dev, putting me as reviewer.

Thanks! (I know the documentation is poor)

**Comment by stemangiola** [comment]
You can link the pull request to this issue, so to keep everything on track ;)
