### ISSUE TITLE
test_gene_overrepresentation: bug or user error

### ISSUE THREAD

**Issue by mblue9** [stemangiola/tidybulk#45]
Was trying out test_gene_overrepresentation using the workshop data. If I do this:

```
counts_de_entrez <- counts_de_pretty %>% 
    filter(!lowly_abundant) %>%
    symbol_to_entrez() 

res <- test_gene_overrepresentation(counts_de_entrez, .do_test=significant, species="human")
```

I get `Error: object '' not found`

Am I doing something wrong or is it a bug?

**Comment by stemangiola** [comment]
Both :)

The correct usage is

```
counts_de_entrez %>% test_gene_overrepresentation(.do_test=significant, species="Homo sapiens", .entrez = entrez)
```

And I was missing few checks (that in a serious language should be done aromatically, e.g. robust arguments missing check)

Merged on dev

**Comment by mblue9** [comment]
Haha well in my defence it said "human" in the help (and thought tidybulk might guess which was the entrez column if it had the expected name entrez)

Thanks for fixing! Have tested and it runs without error now so I'll close this.
