### ISSUE TITLE
Use Authors@R: not Author: in DESCRIPTION

### ISSUE THREAD

**Issue by Alanocallaghan** [stemangiola/tidybulk#50]
On the [Bioc latest page](https://bioconductor.org/packages/3.12/bioc/html/tidybulk.html) the author shows as R code rather than human-readable text. Using the person function only works with Authors@R, which is interpreted during R CMD build.

> Author: person("Stefano", "Mangiola", email=youremail@provider.com, role=c("cre", aut"), comment = c(ORCID = "0000-0001-7474-836X")). 

You'll also need to quote your email address

**Comment by stemangiola** [comment]
Thanks!
