### ISSUE TITLE
add symbol convesion for drosophila gene ID

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidybulk#98]
@mblue9 is this still valid as far as you remember? :)

**Comment by mblue9** [comment]
heya, I don't think it's essential to add it to tidybulk as people could do something like this
```
counts_annot <- mutate(counts_tt, symbol = mapIds(org.Dm.eg.db, keys=feature, keytype = "FLYBASE", column="SYMBOL", multiVals = "first"))
```

**Comment by stemangiola** [comment]
> 
> 
> heya, I don't think it's essential to add it to tidybulk as people could do something like this
> 
> ```
> counts_annot <- mutate(counts_tt, symbol = mapIds(org.Dm.eg.db, keys=feature, keytype = "FLYBASE", column="SYMBOL", multiVals = "first"))
> ```

So you think we should drop ensembl_to_symbol function?

**Comment by mblue9** [comment]
maybe, I don't have a strong feeling to drop it as I understand ensembl_to_symbol might be convenient for people who work with human and mouse but disadvantages are:

 - unclear what annotation is being used, underlying annotation db, version etc (if using mapIds from the org.db package you've loaded to use that then you know)
- ensembl_to_symbol only works for human and mouse, you could make it work for drosophila but people with other species would need an alternative option 
- extra maintenance to keep the annotation up to date for all species included in tidybulk, and also to document how the annotation is obtained and used in the tidybulk ensembl_to_symbol

if annotation can be done in a line or 2 like above with external packages, then maybe better to just do that & instead focus on documenting how people can get the annotation they need from the external packages?

**Comment by stemangiola** [comment]
Yes mostly agree, I can put the function as questioning life cycle
